steps:
  - name: node:18.0.0
    dir: backend/
    entrypoint: npm
    args: ["install"]
  - name: node:18.0.0
    dir: backend/
    entrypoint: npm
    args: ["run", "create-env"]
    env:
      - "MONGO_URL=${_MONGO_URL}"
      - "OAUTH_CLIENT_ID=${_OAUTH_CLIENT_ID}"
      - "OAUTH_CLIENT_SECRET=${_OAUTH_CLIENT_SECRET}"
      - "JWT_PRIVATE_KEY=${_JWT_PRIVATE_KEY}"
      - "STRIPE_PRIVATE_KEY=${_STRIPE_PRIVATE_KEY}"
      - "STRIPE_ENDPOINT=${_STRIPE_ENDPOINT}"
      - "REVERY_PRIVATE_KEY=${_REVERY_PRIVATE_KEY}"
      - "REVERY_PUBLIC_KEY=${_REVERY_PUBLIC_KEY}"
      - "EMAIL_PASSWORD=${_EMAIL_PASSWORD}"
      - "FACEBOOK_ACCESS_TOKEN=${_FACEBOOK_ACCESS_TOKEN}"
      - "FACEBOOK_PIXEL_ID=${_FACEBOOK_PIXEL_ID}"
  - name: "gcr.io/cloud-builders/gcloud"
    dir: backend/
    args: ["app", "deploy", "app.yaml"]
timeout: "1600s"
