class Breathwork {
  final String name;
  final String description;
  final String whenToUse;

  final String emoji;
  final List<int> inOutTimes;
  final List<String> instructions;
  final bool? advanced;

  const Breathwork({
    required this.name,
    required this.description,
    required this.whenToUse,
    required this.emoji,
    required this.inOutTimes,
    required this.instructions,
    this.advanced,
  }) : super();
}

// ignore: constant_identifier_names
const List<Breathwork> BREATHWORKS = [
  Breathwork(
      name: "4-7-8 Breathing",
      description: "Relax and fall asleep",
      whenToUse: "Before bed",
      emoji: '💤',
      inOutTimes: [
        4,
        7,
        8
      ],
      instructions: [
        "Breathe in",
        "Hold",
        "Breathe out",
      ]),
  Breathwork(
      name: "Box Breathing",
      description: "Calm and focus when stressed or anxious",
      whenToUse: "Before a big event",
      emoji: '■',
      inOutTimes: [4, 4, 4, 4],
      instructions: ["Breathe in", "Hold", "Breathe out", "Hold"]),
  Breathwork(
    name: "5-5 Breathing",
    description: "Regain balance and center yourself",
    whenToUse: "When overthinking",
    emoji: '🧘',
    inOutTimes: [5, 5],
    instructions: ["Breathe in", "Breathe out"],
  ),
  Breathwork(
      name: "Long-Exhale Box Breathing",
      description: "When you're winding down after a hectic day.",
      whenToUse: "For winding down",
      emoji: '🛋️',
      inOutTimes: [4, 4, 6, 2],
      instructions: ["Breathe in", "Hold", "Breathe out", "Hold"]),
  Breathwork(
      name: "10-10-10-10 Breathing",
      description: "When clarity feels out of reach",
      whenToUse: "For deep clarity",
      emoji: '🔍',
      inOutTimes: [10, 10, 10, 10],
      instructions: ["Breathe in", "Hold", "Breathe out", "Hold"],
      advanced: true),
  Breathwork(
    name: "2:1 Breathing",
    description: "Deep relaxation and relief from stress.",
    whenToUse: "For deep relaxation",
    emoji: '🔄',
    inOutTimes: [4, 8],
    instructions: ["Breathe in", "Breathe out"],
  ),

  // Breathwork(
  //     name: "Triangle Breathing",
  //     description: "",
  //     whenToUse: "",
  //     emoji: '▲',
  //     inOutTimes: [3, 3, 3],
  //     instructions: ["Breathe in", "Hold", "Breathe out"]),
  // Breathwork(
  //   name: "Quick Breathing",
  //   description: "Increase energy and alertness",
  //   whenToUse: "When feeling sluggish",
  //   emoji: '⚡',
  //   inOutTimes: [
  //     1,
  //     1,
  //     1,
  //     1,
  //     1,
  //     1,
  //     1,
  //     1,
  //     1,
  //     1,
  //     1,
  //     1,
  //     1,
  //     1,
  //     1,
  //     1,
  //     1,
  //     1,
  //     1,
  //     1,
  //     1,
  //     1,
  //     1,
  //     1,
  //     1,
  //     1,
  //     1,
  //     1,
  //     1,
  //     1,
  //     1,
  //     1,
  //     1,
  //     1,
  //     1,
  //     1,
  //     1,
  //     1,
  //     1,
  //     1,
  //     1,
  //     1,
  //     1,
  //     1,
  //     1,
  //     1,
  //     1,
  //     1,
  //     1,
  //     1,
  //     30,
  //   ],
  //   instructions: [
  //     "Breathe in",
  //     "Breathe out",
  //     "Breathe in",
  //     "Breathe out",
  //     "Breathe in",
  //     "Breathe out",
  //     "Breathe in",
  //     "Breathe out",
  //     "Breathe in",
  //     "Breathe out",
  //     "Breathe in",
  //     "Breathe out",
  //     "Breathe in",
  //     "Breathe out",
  //     "Breathe in",
  //     "Breathe out",
  //     "Breathe in",
  //     "Breathe out",
  //     "Breathe in",
  //     "Breathe out",
  //     "Breathe in",
  //     "Breathe out",
  //     "Breathe in",
  //     "Breathe out",
  //     "Breathe in",
  //     "Breathe out",
  //     "Breathe in",
  //     "Breathe out",
  //     "Breathe in",
  //     "Breathe out",
  //     "Breathe in",
  //     "Breathe out",
  //     "Breathe in",
  //     "Breathe out",
  //     "Breathe in",
  //     "Breathe out",
  //     "Breathe in",
  //     "Breathe out",
  //     "Breathe in",
  //     "Breathe out",
  //     "Breathe in",
  //     "Breathe out",
  //     "Breathe in",
  //     "Breathe out",
  //     "Breathe in",
  //     "Breathe out",
  //     "Breathe in",
  //     "Breathe out",
  //     "Breathe in",
  //     "Breathe out",
  //     "Rest & breath normally",
  //   ],
  // ),
];
