import 'dart:math';

List<String> quotes = [
  '"All we have to decide is what to do with the time that is given us." \n- Gandalf',
  "“If you look for the light, you can often find it. But if you look for the dark, that is all you will ever see.” \n– Uncle Iroh",
  "“Hope is something you give yourself. That is the meaning of inner strength.” \n– Uncle Iroh",
  "“It is important to draw wisdom from many sources, otherwise it becomes rigid and stale.” \n– Uncle Iroh",
  "“Pride is not the opposite of shame, but it's source. True humility is the only antidote to shame.” \n– Uncle Iroh",
  "“You can’t always see the light at the end of the tunnel, but if you just keep moving, you will come to a better place.” \n– Uncle Iroh",
  "“True wisdom begins when we accept things as they are.” \n– Tenzin",
  // "“I sit in silence and find whenever I meditate, my fears alleviate, my tears evaporate” \n- J. Cole",
  "“Anything’s possible, you gotta dream like you never seen obstacles.” \n- J. Cole",
  // "“No such thing as a life that’s better than yours, no such thing..” \n- J. Cole",
  "“Life can bring much pain. There are many ways to deal with this pain. Choose wisely.” \n- J. Cole",
  "“I’d rather be happy being myself than sad trying to please everyone else.” \n- J. Cole",
  "“Take a chance, because you never know how perfect something can turn out.” \n- J. Cole",
  "“Muddy water is best cleared by leaving it alone.” \n- Alan Watts",
  "“This is the real secret of life -- to be completely engaged with what you are doing in the here and now.” \n- Alan Watts",
  "“The meaning of life is just to be alive. It is so plain and so obvious and so simple.” \n- Alan Watts",
  "“No amount of anxiety makes any difference to anything that is going to happen.” \n- Alan Watts",
  "“When you are content to be simply yourself and don't compare or compete, everyone will respect you.” \n- Lao Tzu",
  "“Time is a created thing. To say 'I don't have time,' is like saying, 'I don't want to.” \n- Lao Tzu",
  "“Care about what other people think and you will always be their prisoner.” \n- Lao Tzu",
  "“Nature does not hurry, yet everything is accomplished.” \n- Lao Tzu",
  "“To a mind that is still the whole universe surrenders.” \n- Lao Tzu",
  "“If you are anxious you are living in the future. If you are at peace you are living in the present.” \n- Lao Tzu",
  "“Stop leaving and you will arrive. Stop searching and you will see. Stop running away and you will be found.” \n- Lao Tzu",
  "“We’ve all got both light and dark inside us. What matters is the part we choose to act on. That’s who we really are.” \n- Sirius Black",
  "“It does not do to dwell on dreams and forget to live.” \n- Dumbledore",
  "“It is the unknown we fear when we look upon death and darkness, nothing more.” \n- Albus Dumbledore",
  "“It is our choices that show what we truly are, far more than our abilities.” \n- Albus Dumbledore",
  "“Imagination brings bliss at no cost.” \n- Nujabes",
  "“You have power over your mind - not outside events. Realize this, and you will find strength.” \n- Marcus Aurelius",
  "“Dwell on the beauty of life. Watch the stars, and see yourself running with them.” \n- Marcus Aurelius",
  "“The happiness of your life depends upon the quality of your thoughts.” \n- Marcus Aurelius",
  "“It is not death that a man should fear, but he should fear never beginning to live.” \n- Marcus Aurelius",
  "“Our life is what our thoughts make it.” \n- Marcus Aurelius",
  "“The best revenge is not to be like your enemy.” \n- Marcus Aurelius",
  "“Your mind will take the shape of what you frequently hold in thought...” \n- Marcus Aurelius",
  "“Confine yourself to the present.” \n- Marcus Aurelius",
  "“Very little is needed to make a happy life; it is all within yourself in your way of thinking.” \n- Marcus Aurelius",
  "“The mind is definitely something that can be transformed, and meditation is a means to transform it” \n- Dalai Lama",
  "“But in the end it's only a passing thing, this shadow; even darkness must pass.” \n- Samwise Gamgee",
  "“There’s some good in this world, Mr. Frodo, and it’s worth fighting for.” \n- Samwise Gamgee",
  // "“I cannot escape death, but at least I can escape the fear of it.” \n- Epictetus",
  "“Don't explain your philosophy. Embody it.” \n- Epictetus",
  "“There is only one way to happiness and that is to cease worrying about things which are beyond the power or our will.” \n- Epictetus",
  "“If you want to improve, be content to be thought foolish and stupid.” \n- Epictetus",
  "“It's not what happens to you, but how you react to it that matters.” \n- Epictetus",
  "“Wealth consists not in having great possessions, but in having few wants.” \n- Epictetus",
  "“No man is free who is not master of himself.” \n- Epictetus",
  "“You become what you give your attention to.” \n- Epictetus",
  "“Do or do not. There is no try.” \n- Yoda",
  "“Your focus determines your reality.” \n- Qui-Gon Jinn",
  "“What I advise you to do is, not to be unhappy before the crisis comes.” \n- Seneca",
  "“We suffer more often in imagination than in reality.” \n- Seneca",
  "“I've had a lot of worries in my life, most of which never happened.” \n- Mark Twain",
  "“Oh yes, the past can hurt. But, you can either run from it or, learn from it.” \n- Rafiki",
  "“Discovering the truth about ourselves is a lifetime’s work, but it’s worth the effort.” \n- Fred Rogers",
  "“Often when you think you're at the end of something, you're at the beginning of something else.” \n- Fred Rogers",
  "“The greatest gift you ever give is your honest self.” \n- Fred Rogers",
  "“The only thing evil can’t stand is forgiveness.” \n- Fred Rogers",
  "“It's good to be curious about many things.” \n- Fred Rogers",
  "“I am not afraid of storms, for I am learning how to sail my ship.” \n- Louisa May Alcott",
  "“If you look the right way, you can see that the whole world is a garden.” \n- Frances Hodgson Burnett",
  "“Where you tend a rose, my lad, a thistle cannot grow.” \n- Frances Hodgson Burnett",
];

String randomQuote() {
  return quotes[Random().nextInt(quotes.length)];
}
