name: meditate_app
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 4.6.2+41

environment:
  sdk: ">=2.17.5 <3.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

  duration_picker: ^1.1.0+1
  get: ^4.6.5
  audioplayers: ^1.0.1
  ocarina: ^0.1.2
  get_storage: ^2.0.3
  animated_counter: ^1.0.0
  wave: ^0.2.2
  flutter_native_splash: ^2.2.8
  fl_chart: ^0.45.1
  simple_animations: ^4.2.0
  image_cropper: ^1.4.1
  image_picker: ^0.8.3+2
  permission_handler: ^10.0.0
  firebase_core: ^1.13.1
  firebase_core_platform_interface: 4.5.1
  firebase_messaging: ^11.2.7
  intl: ^0.17.0
  flutter_spinkit: ^5.1.0
  flutter_bounce: ^1.1.0
  flame: ^1.3.0
  shimmer: ^2.0.0
  wakelock: ^0.6.2
  flame_audio: ^1.2.0
  flutter_heatmap_calendar: ^1.0.5
  data_connection_checker:
    git:
      url: https://github.com/chornthorn/data_connection_checker.git
      ref: master
  url_launcher: ^6.1.11
  in_app_review: ^2.0.8
  in_app_purchase: ^3.1.11
  carousel_slider: ^4.2.1
  badges: ^2.0.3
  just_audio: ^0.9.36
  purchases_flutter: ^6.21.0
  share_plus: ^6.3.2
  xl: ^0.9.1
  foil: ^0.9.0+1
  animated_text_kit: ^4.2.2
  overlay_tooltip: ^0.2.3
  posthog_flutter: ^4.6.0
  stroke_text: any
  social_share: ^2.3.1
  screenshot: ^1.3.0
  path_provider: ^2.0.11
  facebook_app_events: ^0.19.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^1.0.1
  flutter_launcher_icons: "^0.10.0"

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/app_icon.jpg"
  adaptive_icon_background: "assets/icon_background.png"
  adaptive_icon_foreground: "assets/icon_foreground.png"
  min_sdk_android: 21
  remove_alpha_ios: true

flutter_native_splash:
  # This package generates native code to customize Flutter's default white native splash screen
  # with background color and splash image.
  # Customize the parameters below, and run the following command in the terminal:
  # flutter pub run flutter_native_splash:create
  # To restore Flutter's default white splash screen, run the following command in the terminal:
  # flutter pub run flutter_native_splash:remove

  # color or background_image is the only required parameter.  Use color to set the background
  # of your splash screen to a solid color.  Use background_image to set the background of your
  # splash screen to a png image.  This is useful for gradients. The image will be stretch to the
  # size of the app. Only one parameter can be used, color and background_image cannot both be set.
  background_image: "assets/splash_screen.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/streak_icon.png
    - assets/gem_icon.png
    - assets/enlightenment_cheatsheet.jpeg
    - assets/audio/tibetan_chime.wav
    - assets/audio/new_gems.mp3
    - assets/lotus.png
    - assets/bonsai_circle.png
    - assets/water_vibes.webp
    - assets/lotus2.png
    - assets/turtle_timer.png
    - assets/fire.gif
    - assets/streak_icon_grey.png
    - assets/meditate_selected.png
    - assets/meditate_unselected.png
    - assets/store_selected.png
    - assets/store_unselected.png
    - assets/streak_freeze.png
    - assets/lilypad.png
    - assets/rock.png
    - assets/turtle_lines.png
    - assets/ocean_background.jpeg
    - assets/ocean_foreground.png
    - assets/turtle_selected.png
    - assets/turtle_unselected.png
    - assets/images/turtles/locked.png
    - assets/gems_chest.png
    - assets/audio/water_sounds.mp3
    - assets/streak_icon_yellow.png
    - assets/streak_icon_rainbow.png
    - assets/streak_icon_blue.png
    - assets/egg.png
    - assets/egg_crack_1.png
    - assets/egg_crack_2.png
    - assets/egg_spots.png
    - assets/profile_selected.png
    - assets/profile_unselected.png
    - assets/images/turtles/template.png
    - assets/images/turtles/swim/swim1.png
    - assets/images/turtles/swim/swim2.png
    - assets/images/turtles/0.png
    - assets/images/turtles/1.png
    - assets/images/turtles/2.png
    - assets/images/turtles/3.png
    - assets/images/turtles/4.png
    - assets/images/turtles/5.png
    - assets/images/turtles/6.png
    - assets/images/turtles/7.png
    - assets/images/turtles/8.png
    - assets/images/turtles/9.png
    - assets/images/turtles/10.png
    - assets/images/turtles/10_overlay.png
    - assets/images/turtles/11.png
    - assets/images/turtles/12.png
    - assets/images/turtles/13.png
    - assets/images/turtles/14.png
    - assets/images/turtles/15.png
    - assets/images/turtles/16.png
    - assets/images/turtles/17.png
    - assets/images/turtles/18.png
    - assets/images/turtles/19.png
    - assets/images/turtles/20.png
    - assets/images/turtles/21.png
    - assets/images/turtles/21_underlay.png
    - assets/images/turtles/22.png
    - assets/images/turtles/23.png
    - assets/images/turtles/23_overlay.png
    - assets/images/turtles/overlay_rainbow_default.png
    - assets/images/turtles/overlay_rainbow_crystal.png
    - assets/logo.png
    - assets/audio/egg_crack.wav
    - assets/bubble.png
    - assets/images/game_background.jpeg
    - assets/images/turtle_basic.png
    - assets/images/game/sand.jpeg
    - assets/images/game/water.png
    - assets/images/game/lotus.png
    - assets/images/game/bubble.png
    - assets/images/game/lilypad.png
    - assets/images/game/lilypad2.png
    - assets/images/game/lilypad3.png
    - assets/images/game/lilypad4.png
    - assets/images/game/lilypad5.png
    - assets/images/game/rock.png
    - assets/images/game/fish.png
    - assets/images/game/fish2.png
    - assets/images/game/fish_2.png
    - assets/images/game/fish_2_2.png
    - assets/images/game/insects/butterfly_1.png
    - assets/images/game/insects/butterfly_2.png
    - assets/images/game/insects/butterfly_3.png
    - assets/images/game/starfish_1.png
    - assets/images/game/shell_1.png
    - assets/images/game/water_spritesheet.png
    - assets/images/game/water_spritesheet2.png
    - assets/gems_overlay.png
    - assets/images/game/blue.png
    - assets/offline.png
    - assets/lure.png
    - assets/audio/splash.wav
    - assets/sand_dollar.png
    - assets/sand_dollar_chest.png
    - assets/sand_dollar_overlay.png
    - assets/blank_profile.png
    - assets/ambiences/water_sounds.jpg
    - assets/ambiences/mourning_doves.jpg
    - assets/audio/mourning_doves.mp3
    - assets/stars.jpg
    - assets/audio/night.mp3
    - assets/ambiences/forest.jpg
    - assets/audio/forest.mp3
    - assets/ambiences/random.jpg
    - assets/ambiences/wind.jpg
    - assets/audio/wind.mp3
    - assets/ambiences/rain.jpg
    - assets/audio/rain.mp3
    - assets/images/rainy_overlay.gif
    - assets/ambiences/extradimensional.jpg
    - assets/audio/extradimensional.mp3
    - assets/ambiences/jungle.jpg
    - assets/audio/jungle.mp3
    - assets/ambiences/lostcivilization.jpg
    - assets/audio/lostcivilization.mp3
    - assets/ambiences/prehistoricsea.jpg
    - assets/audio/prehistoricsea.mp3
    - assets/ambiences/underwater.jpg
    - assets/audio/underwater.mp3
    - assets/ambiences/beach.jpg
    - assets/audio/beach.mp3
    - assets/ambiences/thunderstorm.jpg
    - assets/audio/thunderstorm.mp3
    - assets/ambiences/at_chapters_end.png
    - assets/audio/at_chapters_end.mp3
    - assets/jungle_top.png
    - assets/jungle_bottom.png
    - assets/images/game/water_2.gif
    - assets/ambiences/none.jpg
    - assets/streak_revive.png
    - assets/images/game/lilypad_flower.png
    - assets/breathwork_background.jpg
    - assets/instagram.png
    - assets/app_icon.jpg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
